/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseGrafic: typeof import('./src/components/base-grafic.vue')['default']
    BaseHeader: typeof import('./src/components/base-header.vue')['default']
    BaseLayout: typeof import('./src/components/base-layout.vue')['default']
    BaseTable: typeof import('./src/components/base-table.vue')['default']
    ErrorModal: typeof import('./src/components/error-modal.vue')['default']
    Locale: typeof import('./src/components/locale.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFilter: typeof import('./src/components/select-filter.vue')['default']
  }
}
